export declare function required(): void;
export declare function required(customMessage: string): void;
export declare function required(when: (object: object) => boolean): void;
export declare function required(customMessage: string, when: (object: object) => boolean): void;
export declare function satisfiesRule(ruleName: string): void;
export declare function satisfiesRule(ruleName: string, customMessage: string): void;
export declare function satisfiesRule(ruleName: string, when: (object: object) => boolean): void;
export declare function satisfiesRule(ruleName: string, customMessage: string, when: (object: object) => boolean): void;
export declare function satisfies(condition: (value: any, object: object) => boolean | Promise<boolean>): void;
export declare function satisfies(condition: (value: any, object: object) => boolean | Promise<boolean>, customMessage: string): void;
export declare function satisfies(condition: (value: any, object: object) => boolean | Promise<boolean>, when: (object: object) => boolean): void;
export declare function satisfies(condition: (value: any, object: object) => boolean | Promise<boolean>, customMessage: string, when: (object: object) => boolean): void;
export declare function email(): void;
export declare function email(customMessage: string): void;
export declare function email(when: (object: object) => boolean): void;
export declare function email(customMessage: string, when: (object: object) => boolean): void;
export declare function matches(regex: RegExp): void;
export declare function matches(regex: RegExp, customMessage: string): void;
export declare function matches(regex: RegExp, when: (object: object) => boolean): void;
export declare function matches(regex: RegExp, customMessage: string, when: (object: object) => boolean): void;
export declare function minLength(length: number): void;
export declare function minLength(length: number, customMessage: string): void;
export declare function minLength(length: number, when: (object: object) => boolean): void;
export declare function minLength(length: number, customMessage: string, when: (object: object) => boolean): void;
export declare function maxLength(length: number, customMessage: string): void;
export declare function maxLength(length: number, when: (object: object) => boolean): void;
export declare function maxLength(length: number, customMessage: string, when: (object: object) => boolean): void;
export declare function minItems(count: number): void;
export declare function minItems(count: number, customMessage: string): void;
export declare function minItems(count: number, when: (object: object) => boolean): void;
export declare function minItems(count: number, customMessage: string, when: (object: object) => boolean): void;
export declare function maxItems(count: number, customMessage: string): void;
export declare function maxItems(count: number, when: (object: object) => boolean): void;
export declare function maxItems(count: number, customMessage: string, when: (object: object) => boolean): void;
export declare function min(value: number): void;
export declare function min(value: number, customMessage: string): void;
export declare function min(value: number, when: (object: object) => boolean): void;
export declare function min(value: number, customMessage: string, when: (object: object) => boolean): void;
export declare function max(value: number): void;
export declare function max(value: number, customMessage: string): void;
export declare function max(value: number, when: (object: object) => boolean): void;
export declare function max(value: number, customMessage: string, when: (object: object) => boolean): void;
export declare function range(min: number, max: number): void;
export declare function range(min: number, max: number, customMessage: string): void;
export declare function range(min: number, max: number, when: (object: object) => boolean): void;
export declare function range(min: number, max: number, customMessage: string, when: (object: object) => boolean): void;
export declare function between(min: number, max: number): void;
export declare function between(min: number, max: number, customMessage: string): void;
export declare function between(min: number, max: number, when: (object: object) => boolean): void;
export declare function between(min: number, max: number, customMessage: string, when: (object: object) => boolean): void;
export declare function equals(value: any): void;
export declare function equals(value: any, customMessage: string): void;
export declare function equals(value: any, when: (object: object) => boolean): void;
export declare function equals(value: any, customMessage: string, when: (object: object) => boolean): void;
export declare function displayName(customName: string): (targetClass: Object, name: string) => void;
export declare function tag(tag: string): (targetClass: Object, name: string) => void;
